### ISSUE TITLE
Typo in Slack Operation Success Message

### ISSUE THREAD

**Issue by torms3** [seung-lab/seuron#85]
## Description

There is a typo in the success message for the Slack operation. The word "Remaping" should be corrected to "Remapping".

## Location

The typo is located in the following [snippet of code](https://github.com/seung-lab/seuron/blob/79e3d81cebc09f12347662925305cee01f8366d0/dags/segmentation_dags.py#L667):
```python
slack_ops[k]["remap"] = slack_message_op(dag[k], "remap_{}".format(k), ":heavy_check_mark: {}: Remaping finished".format(k))

**Comment by torms3** [comment]
Alex found it and said it was annoying, but he didn't want to bother Ran, who is always super busy. I volunteered to play the villain.

**Comment by jabae** [comment]
Correction: I didn't say I was "annoyed". I said it was catching my eyes. So don't get me wrong:)

**Comment by ranlu** [comment]
Any other typo you noticed? might as well fix them together. BTW, @jabae you can directly make a commit or a pr if you prefer
